### PR TITLE
Adding z3-solver; refactoring how we manage Python packages

### PR DESCRIPTION
**Pull request by jsiirola**
This adds the z3-solver python package, as well as defining key environment variables so that build images can manage / alter the Python environment.

### CODE REVIEW

**Comment by ghackebeil** [comment]
@jsiirola: I believe forks are not allowed to access the secured environment variables, so the docker push step fails. Working on a local branch or directly on master should resolve this.

**Comment by ghackebeil** [comment]
@jsiirola: Write any environment variables whose values need to be obtained by a command to the file `${DYNAMIC_VARS_FILE}` (e.g., see the baron.sh install script). I automatically add these to the environment later. It cannot be done via the dockerfile.

**Comment by ghackebeil** [comment]
example:
```bash
RUN echo GJH_VERSION `Gjh/bin/${TARGET} -v` >> ${DYNAMIC_VARS_FILE}
```

**Comment by jsiirola** [comment]
@ghackebeil: Thanks! (I should really read my email / watch this PR instead of randomly trying things).

I believe that this PR is ready to go.

**Pull request merged**
