### PR TITLE
add bash script for pynumero docker image

### PR DESCRIPTION
**Pull request by santiagoropb**

### CODE REVIEW

**Comment by ghackebeil** [comment]
@santiagoropb: Does miniconda install a new Python executable? If so, then this is probably not something we should incorporate into all of the linux test images. Maybe we should just incorporate the pynumero install into the Anaconda 2 and Anaconda 3 builds, in which case the miniconda install step is not needed. Do you agree?

**Comment by jsiirola** [comment]
@ghackebeil: I agree that we probably shouldn't do this for all builds and restricting it to anaconda builds might be OK.

I have been debating how to support things like pynumero and the MC++ interface.  The challenge is that the compiled library interfaces are built partly from code in the Pyomo repo.  The question is what should we test against: should we build the current code and test against that, or should we test against the currently published libraries?  I think that the former is certainly necessary, but we may only be able to do that on Jenkins (due to the TPL licensing).  The concern with the latter (i.e., this PR).  Most of the time, using the published libraries should be fine, but sometimes the current code will drift and the published libraries will become out of sync and may induce test failures.

FWIW, part of the point of Pyomo/pyomo#819 is to lay the groundwork for this testing.

**Comment by santiagoropb** [comment]
@ghackebeil yes I agree. Where can I look at the Anaconda2 and Anaconda3 builds? Incorporating the pynumero install will be basically to add 

`conda install -c conda-forge pymumps && conda install -c conda-forge pynumero_libraries`

to those builds.

**Comment by ghackebeil** [comment]
@santiagoropb: Is this installing pynumero (i.e., what is in pyomo.contrib) or is it installing thirdparty libraries necessary to test it on our Travis builds? If it is the latter, I think it makes sense to add something like what you have above to the end of this file:
https://github.com/Pyomo/docker_scripts/blob/master/linux_install_scripts/python_libs.sh
It will have to include a conditional to check that `conda` is available (implying that it is an anaconda build). E.g.,
```bash
RUN conda --version &> /dev/null && \
    conda install -c conda-forge pymumps && \
    conda install -c conda-forge pynumero_libraries
```

**Comment by santiagoropb** [comment]
@ghackebeil that installs compiled code used in pynumero. The code in pyomo.contrib.pynumero uses that compiled code when calling the functions from python. So yeah it can be thought of third-party libraries. I'll change the pull request to make the changes you suggest.

**Comment by ghackebeil** [comment]
@santiagoropb: did you still want to make this update?

**Comment by santiagoropb** [comment]
@ghackebeil is there a way to see this working? It only runs on master right? The code coverage of contrib.pynumero should increase if those libraries are being found. I would like to run it with my pull request #804 but if I understood correctly your email this does not work on branches.

**Comment by ghackebeil** [comment]
It only pushes the final images to dockerhub after being merged into master. Once the images are on dockerhub, you should see coverage increase (after running the Travis tests for Pyomo/pyomo).

**Comment by ghackebeil** [comment]
I think this is working now. Unfortunately, the MUMPS server seems to be down again, so the Ipopt install hangs. I'll merge this into master and fire off the builds tomorrow. Hopefully the MUMPS server is up by then.

**Comment by ghackebeil** [comment]
@santiagoropb: The Anaconda DockerHub images now include these additional packages. I've kicked off the Travis tests for Pyomo/pyomo on master. Please verify that you see the coverage changes you expect once those are complete.

**Comment by santiagoropb** [comment]
@ghackebeil: Thanks Gabe, I just checked and coverage of pynumero went from 48% to 82% which is what I was expecting.

**Pull request merged**
